// flow-typed signature: 0c2e3f5b7da40a2cd1aa8cbf9e8d8f8c
// flow-typed version: <<STUB>>/jest-puppeteer_v^3.5.1/flow_v0.83.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jest-puppeteer'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jest-puppeteer' {
  declare module.exports: any;
}
