// flow-typed signature: 0689e1c50b137f8a5fd63f9d631bc59a
// flow-typed version: <<STUB>>/react-render-html_v^0.6.0/flow_v0.76.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-render-html'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-render-html' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-render-html/lib/style-parser' {
  declare module.exports: any;
}

declare module 'react-render-html/test/test-style-parser' {
  declare module.exports: any;
}

declare module 'react-render-html/test/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-render-html/index' {
  declare module.exports: $Exports<'react-render-html'>;
}
declare module 'react-render-html/index.js' {
  declare module.exports: $Exports<'react-render-html'>;
}
declare module 'react-render-html/lib/style-parser.js' {
  declare module.exports: $Exports<'react-render-html/lib/style-parser'>;
}
declare module 'react-render-html/test/test-style-parser.js' {
  declare module.exports: $Exports<'react-render-html/test/test-style-parser'>;
}
declare module 'react-render-html/test/test.js' {
  declare module.exports: $Exports<'react-render-html/test/test'>;
}
