version: 2

jobs:
  build:
    working_directory: ~/designsystem
    docker:
      - image: circleci/node:10.12.0
        environment:
          CI: 1
      - image: browserless/chrome:release-chrome-stable
    steps:
      - checkout
      - restore_cache:
          key: yarndeps-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - run:
          name: Upgrade yarn to 1.12.3
          command: sudo npm install -g yarn@1.12.3
      - run:
          name: Installing javascript dependencies
          command: yarn install --cache-folder ~/.yarn-cache
      - save_cache:
          key: yarndeps-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - ~/.yarn-cache
      - run:
          name: Linting the source code
          command: yarn lint
      - run:
          name: Build packages
          command: yarn build
      - run:
          name: Typechecking the source code
          command: yarn typecheck
      - run:
          name: Testing the source code
          command: yarn test:ci

workflows:
  version: 2
  test:
    jobs:
      - build
